INSERT INTO reddit_threads (reddit_id, subreddit, title, url, permalink, score, num_comments, thumbnail_url, created_utc, rank_score, fetched_at) VALUES
  ('abc123', 'gaming',                  'Elden Ring just got a surprise patch that fixes the PC performance issues',              'https://www.eurogamer.net/elden-ring-patch',           '/r/gaming/comments/abc123/elden_ring_patch',              48200, 1840, null, now() - interval '1 day', 53720, now()),
  ('def456', 'games',                   'Hollow Knight: Silksong has gone gold, release date announced for next month',           'https://www.hollowknight.com/silksong',                '/r/games/comments/def456/silksong_gone_gold',             92100, 3210, null, now() - interval '1 day', 101730, now()),
  ('ghi789', 'pcgaming',                'Steam Spring Sale is live — over 10,000 games discounted up to 90%',                    'https://store.steampowered.com/sale/spring',           '/r/pcgaming/comments/ghi789/steam_spring_sale',           31500,  980, null, now() - interval '1 day', 34440, now()),
  ('jkl012', 'PS5',                     'God of War Ragnarok PC port confirmed, launches this summer',                            'https://www.playstation.com/gow-ragnarok-pc',          '/r/PS5/comments/jkl012/gow_ragnarok_pc',                  55300, 2100, null, now() - interval '1 day', 61600, now()),
  ('mno345', 'pcmasterrace',            'RTX 5080 vs RX 9070 XT — full benchmark comparison at 4K',                              'https://www.digitalfoundry.net/rtx5080-vs-rx9070xt',   '/r/pcmasterrace/comments/mno345/rtx_5080_vs_rx_9070_xt', 18700,  760, null, now() - interval '1 day', 20980, now()),
  ('pqr678', 'GamingLeaksAndRumours',   'GTA 6 release date reportedly pushed to October 2026, sources say',                     'https://www.videogameschronicle.com/gta6-delay',       '/r/GamingLeaksAndRumours/comments/pqr678/gta6_delay',     41000, 3800, null, now() - interval '1 day', 52400, now()),
  ('stu901', 'patientgamers',           'Finished Cyberpunk 2077 + Phantom Liberty last night — what a journey',                  'https://reddit.com/r/patientgamers/comments/stu901',   '/r/patientgamers/comments/stu901/cyberpunk_journey',      12400,  540, null, now() - interval '1 day', 14020, now()),
  ('vwx234', 'playstation',             'PlayStation Plus May 2026 free games revealed',                                          'https://blog.playstation.com/ps-plus-may-2026',        '/r/playstation/comments/vwx234/psplus_may_2026',          24600, 1120, null, now() - interval '1 day', 27960, now()),
  ('yza567', 'Steam',                   'Steam Deck OLED 2 hands-on: brighter display, longer battery, same great form factor',  'https://www.theverge.com/steam-deck-oled-2-hands-on',  '/r/Steam/comments/yza567/steam_deck_oled_2',              35800, 1450, null, now() - interval '1 day', 40150, now()),
  ('bcd890', 'gaming',                  'After 20 years, a fan-made remake of Knights of the Old Republic is finally complete',   'https://www.pcgamer.com/kotor-fan-remake-complete',    '/r/gaming/comments/bcd890/kotor_fan_remake_complete',     78400, 2650, null, now() - interval '1 day', 86350, now());
